'use client';

import { useState, useEffect, useMemo } from 'react';
import { C, SvgIcon, ICONS, showToast } from '../_shared';

// ─── TYPES ──────────────────────────────────────────────────────────────────

interface CalendarEvent {
  id: string;
  meetingId?: string | null;
  leadId?: string | null;
  title: string;
  description?: string;
  date: string;
  time: string;
  duration: number;
  type: 'meeting' | 'follow_up' | 'reminder' | 'email' | 'manual';
  color: string;
  completed: boolean;
  meetingType?: string;
  meetingStatus?: string;
  winLoss?: string;
  autoGenerated?: boolean;
}

type View = 'month' | 'week' | 'day';

const TYPE_LABELS: Record<string, string> = {
  meeting: 'Meeting',
  follow_up: 'Follow-Up',
  reminder: 'Erinnerung',
  email: 'E-Mail',
  manual: 'Eintrag',
};

const WEEKDAYS = ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'];
const MONTHS = [
  'Januar',
  'Februar',
  'März',
  'April',
  'Mai',
  'Juni',
  'Juli',
  'August',
  'September',
  'Oktober',
  'November',
  'Dezember',
];

// ─── HELPERS ────────────────────────────────────────────────────────────────

function getMonday(d: Date): Date {
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  return new Date(d.getFullYear(), d.getMonth(), diff);
}

function isSameDay(a: Date, b: Date): boolean {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}

function dateStr(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function getMonthDays(year: number, month: number): Date[] {
  const first = new Date(year, month, 1);
  const startDay = first.getDay() || 7;
  const start = new Date(year, month, 1 - (startDay - 1));
  const days: Date[] = [];
  for (let i = 0; i < 42; i++) {
    days.push(new Date(start.getFullYear(), start.getMonth(), start.getDate() + i));
  }
  return days;
}

function getWeekDays(monday: Date): Date[] {
  const days: Date[] = [];
  for (let i = 0; i < 7; i++) {
    days.push(new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + i));
  }
  return days;
}

// ─── ADD EVENT MODAL ────────────────────────────────────────────────────────

function AddEventInline({
  date,
  onAdd,
  onCancel,
}: {
  date: string;
  onAdd: (e: { title: string; date: string; time: string; duration: number; type: string }) => void;
  onCancel: () => void;
}) {
  const [title, setTitle] = useState('');
  const [time, setTime] = useState('09:00');
  const [duration, setDuration] = useState(30);

  return (
    <div
      style={{
        padding: '14px 16px',
        borderRadius: 10,
        background: C.surface2,
        border: `1px solid ${C.borderAccent}`,
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
        animation: 'fadeInUp 0.2s ease both',
      }}
    >
      <input
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="Titel…"
        autoFocus
        onKeyDown={(e) => {
          if (e.key === 'Enter' && title.trim()) onAdd({ title, date, time, duration, type: 'manual' });
          if (e.key === 'Escape') onCancel();
        }}
        style={{
          padding: '7px 10px',
          borderRadius: 7,
          background: C.surface,
          border: `1px solid ${C.border}`,
          color: C.text1,
          fontSize: 12,
          fontFamily: 'inherit',
          outline: 'none',
        }}
      />
      <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
        <input
          type="time"
          value={time}
          onChange={(e) => setTime(e.target.value)}
          style={{
            padding: '5px 8px',
            borderRadius: 6,
            background: C.surface,
            border: `1px solid ${C.border}`,
            color: C.text1,
            fontSize: 11,
            fontFamily: 'inherit',
            outline: 'none',
            colorScheme: 'dark',
          }}
        />
        <select
          value={duration}
          onChange={(e) => setDuration(Number(e.target.value))}
          style={{
            padding: '5px 8px',
            borderRadius: 6,
            background: C.surface,
            border: `1px solid ${C.border}`,
            color: C.text1,
            fontSize: 11,
            fontFamily: 'inherit',
            outline: 'none',
          }}
        >
          <option value={15}>15 min</option>
          <option value={30}>30 min</option>
          <option value={45}>45 min</option>
          <option value={60}>60 min</option>
        </select>
        <div style={{ flex: 1 }} />
        <button
          onClick={() => {
            if (title.trim()) onAdd({ title, date, time, duration, type: 'manual' });
          }}
          style={{
            padding: '5px 12px',
            borderRadius: 6,
            background: 'linear-gradient(135deg, #4F46E5, #6366F1)',
            border: 'none',
            color: '#fff',
            fontSize: 11,
            fontWeight: 500,
            cursor: 'pointer',
            fontFamily: 'inherit',
          }}
        >
          Hinzufügen
        </button>
        <button
          onClick={onCancel}
          style={{
            padding: '5px 10px',
            borderRadius: 6,
            background: 'transparent',
            border: `1px solid ${C.border}`,
            color: C.text3,
            fontSize: 11,
            cursor: 'pointer',
            fontFamily: 'inherit',
          }}
        >
          Abbrechen
        </button>
      </div>
    </div>
  );
}

// ─── TODAY WIDGET ────────────────────────────────────────────────────────────

function TodayWidget({ events }: { events: CalendarEvent[] }) {
  const today = dateStr(new Date());
  const todayEvents = events.filter((e) => e.date === today).sort((a, b) => (a.time || '').localeCompare(b.time || ''));
  const upcoming = todayEvents.filter((e) => !e.completed);
  const now = new Date();
  const nowMinutes = now.getHours() * 60 + now.getMinutes();

  // Find next event
  const next = upcoming.find((e) => {
    if (!e.time) return false;
    const [h, m] = e.time.split(':').map(Number);
    return h * 60 + m > nowMinutes;
  });

  const nextIn = next?.time
    ? (() => {
        const [h, m] = next.time.split(':').map(Number);
        const diff = h * 60 + m - nowMinutes;
        return diff < 60 ? `in ${diff} min` : `in ${Math.floor(diff / 60)}h ${diff % 60}m`;
      })()
    : null;

  return (
    <div
      style={{
        background: C.surface,
        border: `1px solid ${C.border}`,
        borderRadius: 12,
        padding: '16px 18px',
        boxShadow: '0 2px 12px rgba(0,0,0,0.15)',
        animation: 'fadeInUp 0.3s ease both',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
        <SvgIcon d={ICONS.calendar} size={13} color={C.accent} />
        <span style={{ fontSize: 13, fontWeight: 600, color: C.text1 }}>Heute</span>
        <span style={{ fontSize: 11, color: C.text3, marginLeft: 'auto' }}>
          {todayEvents.length} {todayEvents.length === 1 ? 'Termin' : 'Termine'}
        </span>
      </div>

      {next && (
        <div
          style={{
            padding: '10px 12px',
            borderRadius: 8,
            background: `${C.accent}06`,
            border: `1px solid ${C.accent}12`,
            marginBottom: 10,
            display: 'flex',
            alignItems: 'center',
            gap: 10,
          }}
        >
          <div
            style={{
              width: 8,
              height: 8,
              borderRadius: '50%',
              background: C.accent,
              animation: 'pulse-live 2s ease-in-out infinite',
            }}
          />
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 12, fontWeight: 500, color: C.text1 }}>{next.title}</div>
            <div style={{ fontSize: 10, color: C.accent, marginTop: 1 }}>
              {next.time} Uhr · {nextIn}
            </div>
          </div>
        </div>
      )}

      {todayEvents.length === 0 && (
        <div style={{ fontSize: 12, color: C.text3, textAlign: 'center', padding: '10px 0' }}>Keine Termine heute</div>
      )}

      {todayEvents.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {todayEvents.map((e) => (
            <div
              key={e.id}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                padding: '6px 8px',
                borderRadius: 6,
                opacity: e.completed ? 0.5 : 1,
              }}
            >
              <div style={{ width: 3, height: 20, borderRadius: 2, background: e.color, flexShrink: 0 }} />
              <span
                style={{
                  fontSize: 10,
                  fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                  color: C.text3,
                  minWidth: 36,
                }}
              >
                {e.time || '—'}
              </span>
              <span
                style={{
                  fontSize: 12,
                  color: e.completed ? C.text3 : C.text1,
                  textDecoration: e.completed ? 'line-through' : 'none',
                  flex: 1,
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                }}
              >
                {e.title}
              </span>
              <span style={{ fontSize: 9, color: C.text3 }}>{e.duration}m</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── MONTH VIEW ─────────────────────────────────────────────────────────────

function MonthView({
  year,
  month,
  events,
  onDayClick,
  onEventClick,
}: {
  year: number;
  month: number;
  events: CalendarEvent[];
  onDayClick: (date: string) => void;
  onEventClick: (event: CalendarEvent) => void;
}) {
  const days = getMonthDays(year, month);
  const today = new Date();
  const eventsByDate = useMemo(() => {
    const map: Record<string, CalendarEvent[]> = {};
    for (const e of events) {
      if (!map[e.date]) map[e.date] = [];
      map[e.date].push(e);
    }
    return map;
  }, [events]);

  return (
    <div>
      {/* Weekday headers */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 1, marginBottom: 4 }}>
        {WEEKDAYS.map((d) => (
          <div
            key={d}
            style={{
              textAlign: 'center',
              fontSize: 10,
              fontWeight: 600,
              color: C.text3,
              padding: '6px 0',
              letterSpacing: '0.06em',
            }}
          >
            {d}
          </div>
        ))}
      </div>

      {/* Days grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 1 }}>
        {days.map((day, i) => {
          const ds = dateStr(day);
          const isCurrentMonth = day.getMonth() === month;
          const isToday = isSameDay(day, today);
          const dayEvents = eventsByDate[ds] ?? [];

          return (
            <div
              key={i}
              onClick={() => onDayClick(ds)}
              style={{
                minHeight: 80,
                padding: '4px 6px',
                borderRadius: 6,
                background: isToday ? `${C.accent}06` : 'transparent',
                border: `1px solid ${isToday ? C.borderAccent : C.border}`,
                cursor: 'pointer',
                transition: 'background 0.15s ease',
                opacity: isCurrentMonth ? 1 : 0.3,
              }}
              onMouseEnter={(e) => {
                if (!isToday) e.currentTarget.style.background = 'rgba(255,255,255,0.02)';
              }}
              onMouseLeave={(e) => {
                if (!isToday) e.currentTarget.style.background = 'transparent';
              }}
            >
              {/* Day number */}
              <div
                style={{
                  fontSize: 11,
                  fontWeight: isToday ? 700 : 500,
                  color: isToday ? C.accent : C.text2,
                  fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                  marginBottom: 2,
                }}
              >
                {day.getDate()}
              </div>

              {/* Events */}
              {dayEvents.slice(0, 3).map((e) => (
                <div
                  key={e.id}
                  onClick={(ev) => {
                    ev.stopPropagation();
                    onEventClick(e);
                  }}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 4,
                    padding: '2px 5px',
                    borderRadius: 4,
                    background: `${e.color}12`,
                    marginBottom: 2,
                    cursor: 'pointer',
                    overflow: 'hidden',
                  }}
                >
                  <div style={{ width: 4, height: 4, borderRadius: '50%', background: e.color, flexShrink: 0 }} />
                  <span
                    style={{
                      fontSize: 9,
                      color: C.text1,
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                      whiteSpace: 'nowrap',
                      textDecoration: e.completed ? 'line-through' : 'none',
                      opacity: e.completed ? 0.5 : 1,
                    }}
                  >
                    {e.time ? `${e.time} ` : ''}
                    {e.title}
                  </span>
                </div>
              ))}
              {dayEvents.length > 3 && (
                <div style={{ fontSize: 9, color: C.text3, paddingLeft: 5 }}>+{dayEvents.length - 3} weitere</div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── WEEK VIEW ──────────────────────────────────────────────────────────────

function WeekView({
  monday,
  events,
  onDayClick,
  onEventClick,
}: {
  monday: Date;
  events: CalendarEvent[];
  onDayClick: (date: string) => void;
  onEventClick: (event: CalendarEvent) => void;
}) {
  const days = getWeekDays(monday);
  const today = new Date();
  const eventsByDate = useMemo(() => {
    const map: Record<string, CalendarEvent[]> = {};
    for (const e of events) {
      if (!map[e.date]) map[e.date] = [];
      map[e.date].push(e);
    }
    return map;
  }, [events]);

  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 8 }}>
      {days.map((day, i) => {
        const ds = dateStr(day);
        const isToday = isSameDay(day, today);
        const dayEvents = (eventsByDate[ds] ?? []).sort((a, b) => (a.time || '').localeCompare(b.time || ''));

        return (
          <div
            key={i}
            style={{
              background: C.surface,
              border: `1px solid ${isToday ? C.borderAccent : C.border}`,
              borderRadius: 10,
              padding: '12px',
              minHeight: 200,
            }}
          >
            {/* Day header */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
              <div>
                <div style={{ fontSize: 9, color: C.text3, fontWeight: 600, letterSpacing: '0.06em' }}>
                  {WEEKDAYS[i]}
                </div>
                <div
                  style={{
                    fontSize: 18,
                    fontWeight: isToday ? 700 : 500,
                    fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                    color: isToday ? C.accent : C.text1,
                    textShadow: isToday ? `0 0 15px ${C.accent}30` : 'none',
                  }}
                >
                  {day.getDate()}
                </div>
              </div>
              <button
                onClick={() => onDayClick(ds)}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer',
                  padding: 2,
                  display: 'flex',
                  opacity: 0.3,
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.opacity = '1';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.opacity = '0.3';
                }}
                title="Eintrag hinzufügen"
              >
                <span style={{ fontSize: 16, color: C.text3, fontWeight: 300 }}>+</span>
              </button>
            </div>

            {/* Events */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              {dayEvents.map((e) => (
                <div
                  key={e.id}
                  onClick={() => onEventClick(e)}
                  style={{
                    padding: '6px 8px',
                    borderRadius: 6,
                    borderLeft: `3px solid ${e.color}`,
                    background: `${e.color}06`,
                    cursor: 'pointer',
                    transition: 'background 0.15s ease',
                    opacity: e.completed ? 0.5 : 1,
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background = `rgba(255,255,255,0.04)`;
                  }}
                  onMouseLeave={(ev) => {
                    ev.currentTarget.style.background = `${e.color}06`;
                  }}
                >
                  {e.time && (
                    <div
                      style={{
                        fontSize: 9,
                        fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                        color: C.text3,
                        marginBottom: 2,
                      }}
                    >
                      {e.time} · {e.duration}m
                    </div>
                  )}
                  <div
                    style={{
                      fontSize: 11,
                      color: C.text1,
                      fontWeight: 500,
                      textDecoration: e.completed ? 'line-through' : 'none',
                    }}
                  >
                    {e.title}
                  </div>
                  <div style={{ fontSize: 9, color: C.text3, marginTop: 1 }}>{TYPE_LABELS[e.type] ?? e.type}</div>
                </div>
              ))}
              {dayEvents.length === 0 && (
                <div
                  onClick={() => onDayClick(ds)}
                  style={{ fontSize: 10, color: C.text3, textAlign: 'center', padding: '12px 0', cursor: 'pointer' }}
                >
                  Frei
                </div>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// ─── DAY VIEW ───────────────────────────────────────────────────────────────

function DayView({
  date,
  events,
  onEventClick,
  onAddClick,
}: {
  date: Date;
  events: CalendarEvent[];
  onEventClick: (event: CalendarEvent) => void;
  onAddClick: () => void;
}) {
  const ds = dateStr(date);
  const dayEvents = events.filter((e) => e.date === ds).sort((a, b) => (a.time || '').localeCompare(b.time || ''));
  const isToday = isSameDay(date, new Date());

  return (
    <div
      style={{
        background: C.surface,
        border: `1px solid ${C.border}`,
        borderRadius: 12,
        padding: '20px 22px',
        boxShadow: '0 2px 12px rgba(0,0,0,0.15)',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18 }}>
        <div
          style={{
            fontSize: 32,
            fontWeight: 700,
            fontFamily: 'ui-monospace, SFMono-Regular, monospace',
            color: isToday ? C.accent : C.text1,
            textShadow: isToday ? `0 0 20px ${C.accent}30` : 'none',
          }}
        >
          {date.getDate()}
        </div>
        <div>
          <div style={{ fontSize: 14, fontWeight: 600, color: C.text1 }}>
            {date.toLocaleDateString('de-DE', { weekday: 'long' })}
          </div>
          <div style={{ fontSize: 12, color: C.text3 }}>
            {date.toLocaleDateString('de-DE', { day: 'numeric', month: 'long', year: 'numeric' })}
          </div>
        </div>
        <div style={{ flex: 1 }} />
        <button
          onClick={onAddClick}
          className="s-ghost"
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 5,
            padding: '7px 14px',
            borderRadius: 8,
            background: 'transparent',
            border: `1px solid ${C.border}`,
            color: C.text2,
            fontSize: 11,
            cursor: 'pointer',
            fontFamily: 'inherit',
          }}
        >
          <span style={{ fontSize: 14, fontWeight: 300 }}>+</span> Eintrag
        </button>
      </div>

      {dayEvents.length === 0 && (
        <div style={{ textAlign: 'center', padding: '30px 0', color: C.text3, fontSize: 12 }}>
          Keine Termine an diesem Tag
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {dayEvents.map((e) => (
          <div
            key={e.id}
            onClick={() => onEventClick(e)}
            className="s-row"
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 14,
              padding: '14px 16px',
              borderRadius: 10,
              borderLeft: `4px solid ${e.color}`,
              background: 'rgba(255,255,255,0.02)',
              border: `1px solid ${C.border}`,
              borderLeftWidth: 4,
              borderLeftColor: e.color,
              cursor: 'pointer',
              opacity: e.completed ? 0.5 : 1,
            }}
          >
            <div style={{ minWidth: 50, textAlign: 'center' }}>
              <div
                style={{
                  fontSize: 16,
                  fontWeight: 600,
                  fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                  color: C.text1,
                }}
              >
                {e.time || '—'}
              </div>
              <div style={{ fontSize: 9, color: C.text3, marginTop: 1 }}>{e.duration} min</div>
            </div>
            <div style={{ width: 1, height: 32, background: C.border }} />
            <div style={{ flex: 1 }}>
              <div
                style={{
                  fontSize: 14,
                  fontWeight: 500,
                  color: C.text1,
                  textDecoration: e.completed ? 'line-through' : 'none',
                }}
              >
                {e.title}
              </div>
              <div
                style={{ fontSize: 11, color: C.text3, marginTop: 2, display: 'flex', alignItems: 'center', gap: 6 }}
              >
                <span
                  style={{
                    padding: '1px 6px',
                    borderRadius: 3,
                    background: `${e.color}10`,
                    fontSize: 9,
                    color: e.color,
                    fontWeight: 500,
                  }}
                >
                  {TYPE_LABELS[e.type] ?? e.type}
                </span>
                {e.meetingType && <span>{e.meetingType}</span>}
                {e.winLoss === 'won' && <span style={{ color: '#34D399' }}>Gewonnen</span>}
                {e.winLoss === 'lost' && <span style={{ color: '#F87171' }}>Verloren</span>}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── MAIN CALENDAR ──────────────────────────────────────────────────────────

export default function CalendarView() {
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [view, setView] = useState<View>('week');
  const [currentDate, setCurrentDate] = useState(new Date());
  const [addingDate, setAddingDate] = useState<string | null>(null);
  const [selectedEvent, setSelectedEvent] = useState<CalendarEvent | null>(null);

  // Fetch events
  useEffect(() => {
    const from = new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1);
    const to = new Date(currentDate.getFullYear(), currentDate.getMonth() + 2, 0);
    fetch(`/api/calendar?from=${dateStr(from)}&to=${dateStr(to)}`)
      .then((r) => r.json())
      .then((d) => {
        if (d.events) setEvents(d.events);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [currentDate.getMonth(), currentDate.getFullYear()]);

  const navigateMonth = (dir: number) => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + dir, 1));
  };

  const navigateWeek = (dir: number) => {
    const d = new Date(currentDate);
    d.setDate(d.getDate() + dir * 7);
    setCurrentDate(d);
  };

  const navigateDay = (dir: number) => {
    const d = new Date(currentDate);
    d.setDate(d.getDate() + dir);
    setCurrentDate(d);
  };

  const handleAddEvent = async (e: { title: string; date: string; time: string; duration: number; type: string }) => {
    try {
      const res = await fetch('/api/calendar', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(e),
      });
      const data = await res.json();
      if (data.event) {
        setEvents((prev) => [
          ...prev,
          {
            ...data.event,
            id: data.event.id,
            color: '#A78BFA',
            completed: false,
            time: (data.event.time ?? '').slice(0, 5),
          },
        ]);
        showToast('Eintrag erstellt', 'success');
      }
    } catch {
      showToast('Fehler beim Erstellen', 'error');
    }
    setAddingDate(null);
  };

  const handleDayClick = (date: string) => {
    if (view === 'month') {
      setCurrentDate(new Date(date));
      setView('day');
    } else {
      setAddingDate(date);
    }
  };

  const monday = getMonday(currentDate);

  const views: { id: View; label: string }[] = [
    { id: 'month', label: 'Monat' },
    { id: 'week', label: 'Woche' },
    { id: 'day', label: 'Tag' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
      {/* Header: navigation + view switcher */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        {/* Nav */}
        <button
          onClick={() => {
            if (view === 'month') navigateMonth(-1);
            else if (view === 'week') navigateWeek(-1);
            else navigateDay(-1);
          }}
          style={{
            background: 'none',
            border: `1px solid ${C.border}`,
            borderRadius: 7,
            width: 32,
            height: 32,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
          }}
        >
          <span style={{ color: C.text2, fontSize: 14 }}>‹</span>
        </button>

        <div style={{ minWidth: 180, textAlign: 'center' }}>
          <span style={{ fontSize: 15, fontWeight: 600, color: C.text1 }}>
            {view === 'month' && `${MONTHS[currentDate.getMonth()]} ${currentDate.getFullYear()}`}
            {view === 'week' &&
              `${monday.getDate()}. ${MONTHS[monday.getMonth()].slice(0, 3)} — ${new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + 6).getDate()}. ${MONTHS[new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + 6).getMonth()].slice(0, 3)}`}
            {view === 'day' &&
              currentDate.toLocaleDateString('de-DE', { weekday: 'long', day: 'numeric', month: 'long' })}
          </span>
        </div>

        <button
          onClick={() => {
            if (view === 'month') navigateMonth(1);
            else if (view === 'week') navigateWeek(1);
            else navigateDay(1);
          }}
          style={{
            background: 'none',
            border: `1px solid ${C.border}`,
            borderRadius: 7,
            width: 32,
            height: 32,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
          }}
        >
          <span style={{ color: C.text2, fontSize: 14 }}>›</span>
        </button>

        <button
          onClick={() => setCurrentDate(new Date())}
          className="s-ghost"
          style={{
            padding: '6px 12px',
            borderRadius: 7,
            background: 'transparent',
            border: `1px solid ${C.border}`,
            color: C.text2,
            fontSize: 11,
            cursor: 'pointer',
            fontFamily: 'inherit',
          }}
        >
          Heute
        </button>

        <div style={{ flex: 1 }} />

        {/* View switcher */}
        <div
          style={{
            display: 'flex',
            gap: 2,
            padding: 2,
            borderRadius: 8,
            background: 'rgba(255,255,255,0.02)',
            border: `1px solid ${C.border}`,
          }}
        >
          {views.map((v) => {
            const active = view === v.id;
            return (
              <button
                key={v.id}
                onClick={() => setView(v.id)}
                className="s-tab"
                style={{
                  padding: '6px 14px',
                  borderRadius: 6,
                  border: 'none',
                  background: active ? C.accentGhost : 'transparent',
                  color: active ? C.accentBright : C.text3,
                  fontSize: 11,
                  fontWeight: active ? 500 : 400,
                  cursor: 'pointer',
                  fontFamily: 'inherit',
                }}
              >
                {v.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Quick stats bar */}
      <div style={{ display: 'flex', gap: 10 }}>
        {[
          {
            label: 'Diese Woche',
            value: String(
              events.filter((e) => {
                const d = new Date(e.date);
                const m = getMonday(new Date());
                return d >= m && d <= new Date(m.getFullYear(), m.getMonth(), m.getDate() + 6);
              }).length
            ),
            color: '#818CF8',
          },
          {
            label: 'Heute',
            value: String(events.filter((e) => e.date === dateStr(new Date())).length),
            color: '#34D399',
          },
          {
            label: 'Follow-Ups',
            value: String(events.filter((e) => e.type === 'follow_up' && !e.completed).length),
            color: '#38BDF8',
          },
          { label: 'Abgeschlossen', value: String(events.filter((e) => e.completed).length), color: '#A78BFA' },
        ].map((s) => (
          <div
            key={s.label}
            style={{
              flex: 1,
              display: 'flex',
              alignItems: 'center',
              gap: 10,
              padding: '10px 14px',
              borderRadius: 9,
              background: C.surface,
              border: `1px solid ${C.border}`,
            }}
          >
            <span
              style={{
                fontSize: 18,
                fontWeight: 700,
                fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                color: s.color,
              }}
            >
              {s.value}
            </span>
            <span style={{ fontSize: 11, color: C.text3 }}>{s.label}</span>
          </div>
        ))}
      </div>

      {/* Today widget as horizontal bar */}
      <TodayWidget events={events} />

      {/* Add event inline */}
      {addingDate && <AddEventInline date={addingDate} onAdd={handleAddEvent} onCancel={() => setAddingDate(null)} />}

      {/* Calendar — full width */}
      <div style={{ display: 'grid', gridTemplateColumns: selectedEvent ? '1fr 280px' : '1fr', gap: 14 }}>
        <div>
          {view === 'month' && (
            <MonthView
              year={currentDate.getFullYear()}
              month={currentDate.getMonth()}
              events={events}
              onDayClick={handleDayClick}
              onEventClick={setSelectedEvent}
            />
          )}
          {view === 'week' && (
            <WeekView monday={monday} events={events} onDayClick={handleDayClick} onEventClick={setSelectedEvent} />
          )}
          {view === 'day' && (
            <DayView
              date={currentDate}
              events={events}
              onEventClick={setSelectedEvent}
              onAddClick={() => setAddingDate(dateStr(currentDate))}
            />
          )}
        </div>

        {/* Selected event sidebar — only when clicked */}
        {selectedEvent && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div
              style={{
                background: C.surface,
                border: `1px solid ${selectedEvent.color}20`,
                borderRadius: 12,
                padding: '18px 20px',
                boxShadow: '0 2px 12px rgba(0,0,0,0.15)',
                animation: 'fadeInUp 0.2s ease both',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
                <span style={{ fontSize: 10, fontWeight: 600, color: selectedEvent.color, letterSpacing: '0.06em' }}>
                  {(TYPE_LABELS[selectedEvent.type] ?? selectedEvent.type).toUpperCase()}
                </span>
                <button
                  onClick={() => setSelectedEvent(null)}
                  style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 2, display: 'flex' }}
                >
                  <SvgIcon d={ICONS.x} size={12} color={C.text3} />
                </button>
              </div>
              <div style={{ fontSize: 16, fontWeight: 600, color: C.text1, marginBottom: 8 }}>
                {selectedEvent.title}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {[
                  {
                    icon: ICONS.calendar,
                    value: new Date(selectedEvent.date).toLocaleDateString('de-DE', {
                      weekday: 'long',
                      day: 'numeric',
                      month: 'long',
                    }),
                  },
                  selectedEvent.time
                    ? { icon: ICONS.clock, value: `${selectedEvent.time} Uhr · ${selectedEvent.duration} min` }
                    : null,
                  selectedEvent.meetingType ? { icon: ICONS.mic, value: selectedEvent.meetingType } : null,
                  selectedEvent.winLoss === 'won' ? { icon: ICONS.check, value: 'Deal gewonnen' } : null,
                  selectedEvent.winLoss === 'lost' ? { icon: ICONS.x, value: 'Deal verloren' } : null,
                ]
                  .filter(Boolean)
                  .map((item, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <SvgIcon d={(item as { icon: string }).icon} size={12} color={C.text3} />
                      <span style={{ fontSize: 12, color: C.text2 }}>{(item as { value: string }).value}</span>
                    </div>
                  ))}
              </div>
              {selectedEvent.meetingId && (
                <button
                  onClick={() => setSelectedEvent(null)}
                  className="s-primary"
                  style={{
                    width: '100%',
                    marginTop: 14,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: 6,
                    padding: '9px 16px',
                    borderRadius: 9,
                    background: 'linear-gradient(135deg, #4F46E5, #6366F1)',
                    border: 'none',
                    color: '#fff',
                    fontSize: 12,
                    fontWeight: 500,
                    cursor: 'pointer',
                    fontFamily: 'inherit',
                  }}
                >
                  <SvgIcon d={ICONS.chevRight} size={11} color="#fff" />
                  Meeting öffnen
                </button>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Legend — compact horizontal */}
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', padding: '8px 0' }}>
        {[
          { color: '#818CF8', label: 'Video' },
          { color: '#FBBF24', label: 'Telefon' },
          { color: '#34D399', label: 'Vor Ort' },
          { color: '#F87171', label: 'Verloren' },
          { color: '#38BDF8', label: 'Follow-Up' },
          { color: '#A78BFA', label: 'Manuell' },
        ].map((l) => (
          <div key={l.label} style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <div style={{ width: 6, height: 6, borderRadius: 2, background: l.color }} />
            <span style={{ fontSize: 10, color: C.text3 }}>{l.label}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
