import { createServerSupabaseClient } from '@/lib/supabase-server';
import { getSessionTenantId } from '@/lib/tenant-server';
import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

// ─── GET: All calendar events (meetings + manual + auto-generated) ──────────

export async function GET(req: NextRequest) {
  const tenantId = await getSessionTenantId();
  if (!tenantId) return NextResponse.json({ events: [] }, { status: 401 });

  const url = new URL(req.url);
  const from = url.searchParams.get('from');
  const to = url.searchParams.get('to');

  const supabase = await createServerSupabaseClient();

  // 1. Fetch meetings as calendar events
  let meetingsQuery = supabase
    .from('meetings')
    .select('id, title, date, time, duration, type, status, lead_id, win_loss')
    .eq('tenant_id', tenantId);
  if (from) meetingsQuery = meetingsQuery.gte('date', from);
  if (to) meetingsQuery = meetingsQuery.lte('date', to);
  const { data: meetings } = await meetingsQuery.order('date').limit(200);

  // 2. Fetch manual/auto calendar events
  let eventsQuery = supabase.from('calendar_events').select('*').eq('tenant_id', tenantId);
  if (from) eventsQuery = eventsQuery.gte('date', from);
  if (to) eventsQuery = eventsQuery.lte('date', to);
  const { data: calEvents } = await eventsQuery.order('date').limit(200);

  // 3. Fetch leads with follow_up_at
  const { data: followUps } = await supabase
    .from('leads')
    .select('id, first_name, last_name, company_name, follow_up_at')
    .eq('tenant_id', tenantId)
    .not('follow_up_at', 'is', null)
    .limit(50);

  // Transform meetings into calendar events
  const meetingEvents = (meetings ?? []).map((m: Record<string, unknown>) => ({
    id: `mtg-${m.id}`,
    meetingId: m.id,
    title: m.title,
    date: m.date,
    time: ((m.time as string) ?? '').slice(0, 5),
    duration: m.duration,
    type: 'meeting',
    color:
      m.status === 'Abgeschlossen'
        ? m.win_loss === 'won'
          ? '#34D399'
          : m.win_loss === 'lost'
            ? '#F87171'
            : '#818CF8'
        : m.type === 'Video'
          ? '#818CF8'
          : m.type === 'Telefon'
            ? '#FBBF24'
            : '#34D399',
    completed: m.status === 'Abgeschlossen',
    meetingType: m.type,
    meetingStatus: m.status,
    winLoss: m.win_loss,
  }));

  // Transform follow-ups into calendar events
  const followUpEvents = (followUps ?? [])
    .filter((l: Record<string, unknown>) => l.follow_up_at)
    .map((l: Record<string, unknown>) => {
      const d = new Date(l.follow_up_at as string);
      return {
        id: `fu-${l.id}`,
        leadId: l.id,
        title: `Follow-Up: ${l.first_name} ${l.last_name} (${l.company_name})`,
        date: d.toISOString().slice(0, 10),
        time: d.toTimeString().slice(0, 5),
        duration: 15,
        type: 'follow_up',
        color: '#38BDF8',
        completed: false,
      };
    });

  // Manual/auto events
  const manualEvents = (calEvents ?? []).map((e: Record<string, unknown>) => ({
    id: e.id,
    meetingId: e.meeting_id ?? null,
    leadId: e.lead_id ?? null,
    title: e.title,
    description: e.description,
    date: e.date,
    time: ((e.time as string) ?? '').slice(0, 5),
    duration: e.duration,
    type: e.type,
    color: e.color ?? '#A78BFA',
    completed: e.completed,
    autoGenerated: e.auto_generated,
  }));

  return NextResponse.json({
    events: [...meetingEvents, ...followUpEvents, ...manualEvents],
  });
}

// ─── POST: Create manual calendar event ─────────────────────────────────────

export async function POST(req: NextRequest) {
  const tenantId = await getSessionTenantId();
  if (!tenantId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await req.json();
  const { title, description, date, time, duration, type, color } = body;

  if (!title || !date) {
    return NextResponse.json({ error: 'Title and date required' }, { status: 400 });
  }

  const supabase = await createServerSupabaseClient();
  const { data, error } = await supabase
    .from('calendar_events')
    .insert({
      tenant_id: tenantId,
      title,
      description: description ?? '',
      date,
      time: time ?? null,
      duration: duration ?? 30,
      type: type ?? 'manual',
      color: color ?? null,
      auto_generated: false,
    })
    .select()
    .single();

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ event: data }, { status: 201 });
}

// ─── DELETE ─────────────────────────────────────────────────────────────────

export async function DELETE(req: NextRequest) {
  const tenantId = await getSessionTenantId();
  if (!tenantId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await req.json();
  if (!id) return NextResponse.json({ error: 'ID required' }, { status: 400 });

  const supabase = await createServerSupabaseClient();
  await supabase.from('calendar_events').delete().eq('id', id).eq('tenant_id', tenantId);
  return NextResponse.json({ success: true });
}
